# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pythonTraining\QandA\MAIN.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(671, 464)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(7, 10, 660, 451))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setAutoFillBackground(True)
        self.tab.setObjectName("tab")
        self.pushButtonGo = QtWidgets.QPushButton(self.tab)
        self.pushButtonGo.setGeometry(QtCore.QRect(529, 1, 101, 41))
        self.pushButtonGo.setObjectName("pushButtonGo")
        self.labelCorrectNumber = QtWidgets.QLabel(self.tab)
        self.labelCorrectNumber.setGeometry(QtCore.QRect(440, 0, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        self.labelCorrectNumber.setFont(font)
        self.labelCorrectNumber.setObjectName("labelCorrectNumber")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(288, -7, 161, 61))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lcdNumber = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber.setGeometry(QtCore.QRect(160, 12, 101, 31))
        self.lcdNumber.setAutoFillBackground(False)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.labell = QtWidgets.QLabel(self.tab)
        self.labell.setGeometry(QtCore.QRect(17, 1, 141, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(24)
        self.labell.setFont(font)
        self.labell.setObjectName("labell")
        self.labelQ = QtWidgets.QLabel(self.tab)
        self.labelQ.setGeometry(QtCore.QRect(200, 140, 261, 101))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(28)
        self.labelQ.setFont(font)
        self.labelQ.setObjectName("labelQ")
        self.pushButtonWrong = QtWidgets.QPushButton(self.tab)
        self.pushButtonWrong.setGeometry(QtCore.QRect(320, 350, 161, 23))
        self.pushButtonWrong.setObjectName("pushButtonWrong")
        self.pushButtonRight = QtWidgets.QPushButton(self.tab)
        self.pushButtonRight.setGeometry(QtCore.QRect(144, 350, 171, 23))
        self.pushButtonRight.setObjectName("pushButtonRight")
        self.label_Member = QtWidgets.QLabel(self.tab)
        self.label_Member.setGeometry(QtCore.QRect(280, 80, 181, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        self.label_Member.setFont(font)
        self.label_Member.setObjectName("label_Member")
        self.pushButtonGo.raise_()
        self.labelCorrectNumber.raise_()
        self.label.raise_()
        self.lcdNumber.raise_()
        self.labell.raise_()
        self.pushButtonWrong.raise_()
        self.labelQ.raise_()
        self.pushButtonRight.raise_()
        self.labelQ.raise_()
        self.pushButtonWrong.raise_()
        self.pushButtonRight.raise_()
        self.label_Member.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableView = QtWidgets.QTableView(self.tab_2)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 631, 401))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.tableView.setFont(font)
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonGo.setText(_translate("Dialog", "开始游戏！"))
        self.labelCorrectNumber.setText(_translate("Dialog", "0"))
        self.label.setText(_translate("Dialog", "答对题数："))
        self.labell.setText(_translate("Dialog", "剩余时间："))
        self.labelQ.setText(_translate("Dialog", "猜！猜！猜!"))
        self.pushButtonWrong.setText(_translate("Dialog", "错/下一题"))
        self.pushButtonRight.setText(_translate("Dialog", "答对了！"))
        self.label_Member.setText(_translate("Dialog", "等待挑战者！"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "游戏内容"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "排名"))

